export NotFoundPage from './NotFoundPage/NotFoundPage.js';
export Home from './Home/Home.js';
export Header from './Header/Header.js';
export Footer from './Footer/Footer.js';
export EuroCup from './EuroCup/EuroCup.js';
export GroupStage from './GroupStage/GroupStage.js';
export SelectStage from './SelectStage/SelectStage.js';
export TeamPoints from './TeamPoints/TeamPoints.js';
export BestPicks from './BestPicks/BestPicks.js';
export Pot from './Pot/Pot.js';
export GitHubRibbon from './GitHubRibbon/GitHubRibbon.js';
export Rules from './Rules/Rules.js'
